### ISSUE TITLE
Unable to Take Survey through dashboard

### ISSUE THREAD

**Issue by twelch** [Ecotrust/solomon#101]
In production with Chrome, I'm unable to take a survey when following the Take Survey link in the dashboard.  It takes me for example to this URL, note the double slash before the offline - 

http://simarketsurvey.herokuapp.com/static/survey/mobile.html#/survey/volume-and-origin//offline.

Removing the double slash redirects me to the mobile home which seems ok: https://simarketsurvey-test.herokuapp.com/static/survey/mobile.html#/

When I try to start a volume survey however it just takes me back to the home page

**Comment by eknuth** [comment]
This is done.  Each question has an edit button in the respondent detail page.

**Comment by eknuth** [comment]
Sorry, wrong issue.  Starting a survey through the dashboard is available from the "take a survey" menu.

**Comment by twelch** [comment]
Right, take a survey link doesn't seem to be working properly.

**Comment by twelch** [comment]
See my original issue description

**Comment by twelch** [comment]
Ok take survey does seem to be working now, thanks.  Seeing a bug with edit though, I added a value for 'how many eskies of each size' to this survey and it look like there's now two answer records, the original with no value, and another with my given value.

https://simarketsurvey.herokuapp.com/dash#/RespondantDetail/volume-and-origin/offline_1374210416737
