### ISSUE TITLE
Change Heroku app name to hapifis

### ISSUE THREAD

**Issue by twelch** [Ecotrust/solomon#103]
Currently simarketsurvey, realizing it should be hapifis

**Comment by twelch** [comment]
the apk name in turn should also be hapifis

**Comment by eknuth** [comment]
Nice, easy to change through the heroku interface!

**Comment by eknuth** [comment]
We can do this whenever you like.  Test first, for sure.

**Comment by twelch** [comment]
Les do it tomorrow yo
