### ISSUE TITLE
pages need registration flag

### ISSUE THREAD

**Issue by timglaser** [Ecotrust/solomon#135]

**Comment by timglaser** [comment]
I added a attach_to_profile boolean to the Question model. This felt right when it comes to loading and saving profile questions. @eknuth, we discussed this being a per page flag. I'm still feeling like per question is more appropriate to provide the flexibility of mixing profile and non-profile questions within a given page. But I'm certainly open to this being changed it if makes sense. But if it makes sense to leave it as a per question flag, then this issue can closed.

**Comment by eknuth** [comment]
Yeah, I think per question is the right way to go.

**Comment by sfletche** [comment]
need to test on desktop version

**Comment by sfletche** [comment]
authoring tool now offers Registration checkbox for each question
