### ISSUE TITLE
on submit of survey, save profile answers

### ISSUE THREAD

**Issue by timglaser** [Ecotrust/solomon#136]

**Comment by timglaser** [comment]
New registration approach is in place.

Create a new user to test . For some reason you need to register, logout, login. Entered bug as #139.

Any question can be designated as a profile question by checking "Attach to profile" under the slug field in django admin UI. Stored answers to profile questions can be shared across surveys by using the same question slug. Questions marked as profile questions will be pre-populated with most recent answer from any survey.

I tested this for the offline version. I'm having trouble being able to take a survey with the online version. So no testing there yet.

Profile questions are net yet authored into a fixture.

Holding off on closing this until it is tested for online version as well.

**Comment by sfletche** [comment]
need to test on desktop version

**Comment by sfletche** [comment]
working on mobile app.
closing ticket
