### ISSUE TITLE
Authorization error on submitting surveys

### ISSUE THREAD

**Issue by timglaser** [Ecotrust/solomon#138]
Steps to reproduce:
1. Create a new user through the mobile version of the tool (in other words, don't use the Django admin to create the new user)
2. Take the Did not fish survey
3. Submit the survey. The submit progress does not progrss. Notice a 401 error (authorization error) in the javascript console.

If you use a use a django admin superuser instead, the surveys will submit. However, if you look in the admin at the Responses, the Respondent field will say "No Respondent" for each survey submitted via the offline tool.

**Comment by eknuth** [comment]
Ok, the submit function is working for non staff users.  Responses are linked to respondants and the surveyor is correct.

I added the boilder plate per user authorization, but we need to link it up with responses and respondants.  I've started adding users to responses and respondants and removed the surveyor field.

**Comment by eknuth** [comment]
Successful submits online and offline.

**Comment by sfletche** [comment]
fixed
