### ISSUE TITLE
Map Question 

### ISSUE THREAD

**Issue by sfletche** [Ecotrust/solomon#146]
shapefiles of catch grid are in the USVI_map_files zip file in the USVI folder on Google docs

**Comment by sfletche** [comment]
used a 2.5 minute grid (converted to geojson with ogr2ogr) with ET_Index as the label/field value
used ogr2ogr to create the geojson for the grid
user can select and deselect grid cells via click events
this grid only covers USVI (does not cover PR)
used tilemill to generate mbtiles for the labels which are then served via tilestream on ninkasi

**Comment by sfletche** [comment]
note:  had to implement a strategy for solving a problem in which the origin was bottom-left instead of top-left and the y values in mbtiles were flipped (in terms of point of origin)
found and used the strategy found here:
https://gist.github.com/YenTheFirst/993639

**Comment by sfletche** [comment]
alternative strategies to the mbtiles issue could include using mb-utils to create the actual png's (although this would take up a bit of space).

**Comment by sfletche** [comment]
remaining issues to be resolved include labeling, location the correct grid (or verification on the grid we have in place), and determining which attribute should be used as the grid cell identifier.

**Comment by eknuth** [comment]
From report:
A note about mapped areas, it sounds like the are a combination of a letter, I here J and Q a lot and then a number. I'm thinking that we split up the letter and numbers and have a drop down list of the available letters and then enter the coo responding number. I guess it depends on how many letters there are.
