### ISSUE TITLE
saving edited question acts as if it doesn't save

### ISSUE THREAD

**Issue by sfletche** [Ecotrust/solomon#147]
(even though it actually does)
clicking save returns the visible field values back to their original state, while actually saving the new entries as can be demonstrated by refreshing the browser page

**Comment by eknuth** [comment]
Can't seem to reproduce this.  Saving seems to save :(

**Comment by sfletche** [comment]
Behind the scenes, it does save, but to the user of the authoring tool it looks as though it didn't.

This can be reproduced by checking/unchecking Profile, Required, or Visualize on any question and then hitting save.   On the server the question is updated (and this update can be seen by refreshing the browser), but on the authoring tool itself it appears as though the checkbox has returned to its original state.

**Comment by sfletche** [comment]
Note:  this is a problem on the authoring tool (not the survey)

**Comment by sfletche** [comment]
fixed.
