### ISSUE TITLE
Validation in grids

### ISSUE THREAD

**Issue by twelch** [Ecotrust/solomon#15]
Validation not currently happening, maybe not for any of the other option types also.  See transport costs questions in honiara for example

**Comment by eknuth** [comment]
This would be great to move to another milestone.  Not a lot of bang for a lot of work.

**Comment by eknuth** [comment]
Validating required text, integer, number, multiselect.  Do we want min/maxes on numbers, too?

**Comment by twelch** [comment]
Yes, same ability in grids as single

**Comment by twelch** [comment]
If we can do the min/max then I think we're looking pretty good on this
