### ISSUE TITLE
Ensure validation working

### ISSUE THREAD

**Issue by twelch** [Ecotrust/solomon#152]
Required and not, question type, min/max, etc.

**Comment by eknuth** [comment]
continue validation for:
single-select

=Datepicker:
The datepicker is a little off.  I haven't tested it on a samsung, but if you:
- enter a date
- continue
- go back
- clear the date
- continue
  It will allow a blank date to be submitted.

=Grid validation
Single select grid not respecting required flag.
Currency not respecting required flag.
Integer not respecting required flag.

**Comment by eknuth** [comment]
Grid validation has been checked and problems have been resolved.  Functions as expected.
