### ISSUE TITLE
Back button to grid question borking

### ISSUE THREAD

**Issue by twelch** [Ecotrust/solomon#165]
After finishing the cost grid question for the reef fish market survey, going back gives me a blank page body with {{survey.name}} at the top.  Not reloading properly.  Probably the same issue as resuming a grid question ticket #160

**Comment by eknuth** [comment]
Was expecting all grid questions to be selects when reloading the question.  Was trying to loop through the answers even if it was a number or string.  Fixed, reloading grids on resume and back.  Deployed to prod and test.
