### ISSUE TITLE
map image at bottom of home page

### ISSUE THREAD

**Issue by sfletche** [Ecotrust/solomon#168]
Map at the bottom is set too far to the north (I see the word ‘British’ at the very bottom of the map – Puerto Rico and the Virgin Islands are all off the map to the south) (note – the map becomes centered if I scroll the whole page up – as if the map is centered based on the assumption that it is much taller than it actually is when I am viewing the home page)

Sizing on different devices is proving problematic...
Will likely switch to static images

**Comment by sfletche** [comment]
PR and USVI in the same view

**Comment by cheryltchen** [comment]
Do we will need this ticket?
