### ISSUE TITLE
Grid component not visible in mobile app 

### ISSUE THREAD

**Issue by sfletche** [Ecotrust/solomon#170]
Grid component not visible in mobile app (at least not in the browser)

**Comment by eknuth** [comment]
I think I got this figured out. Looks like a watch I put in for validation :(

Scott Fletcher notifications@github.com wrote:

Grid component not visible in mobile app (at least not in the browser)

**Comment by eknuth** [comment]
We lost all the grid_cols.  They have been added back and grids are working.
