### ISSUE TITLE
final page in survey

### ISSUE THREAD

**Issue by sfletche** [Ecotrust/solomon#172]
Last screen currently says ‘you have completed the survey and it is being submitted’

Might prefer a screen that says ‘you have completed the survey’ and then a button to click to submit (just in case the user wants to edit before submitting)

**Comment by sfletche** [comment]
also, change 'survey' to 'catch report'

**Comment by eknuth** [comment]
Added a button to submit.  Changed survey to catch report.

**Comment by sfletche** [comment]
awesome.
what do you think about a spinner while report is submitting?
