### ISSUE TITLE
Pages (all) suddenly lose their skip blocks

### ISSUE THREAD

**Issue by sfletche** [Ecotrust/solomon#177]
Occasionally and for reasons unknown (possibly related to the creation of new pages…?) all block assignments are lost and have to be re-entered via the admin (which is a royal pain now that there are nearly 60 pages)

**Comment by eknuth** [comment]
Still?  This should be fixed :(

Scott Fletcher notifications@github.com wrote:

Occasionally and for reasons unknown (possibly related to the creation of new pages…?) all block assignments are lost and have to be re-entered via the admin (which is a royal pain now that there are nearly 60 pages)

**Comment by sfletche** [comment]
Fixed.
Problem was with re-ordering questions and/or pages in authoring tool.
There is also now a management command in place in case this ever happens again.
It's available in a management command called "fix_questions".  It uses the name of the slug to figure out the correct blocks.
