### ISSUE TITLE
Survey submit returning error

### ISSUE THREAD

**Issue by twelch** [Ecotrust/solomon#187]
Returned: {"error": ["'' value must be a decimal number."]}
Payload: https://gist.github.com/twelch/98c39ddc939af6c6f12a#file-hapi-error

Repeatable by taking a survey and answering 'bought' and 'by the pound'
There is one combination where it doesn't happen that could help narrow the question group causing

**Comment by twelch** [comment]
Ok the issue is questions 25, 26, and 27, the 'how many fish remaining on day 2, 3 and spoilage'.  They are set to not required and are of type number.  The app correctly lets me not fill in these values but when I submit the server-side it's probably trying to verify it's a number and it's blank.

**Comment by eknuth** [comment]
Ok, good to go.  The changes made for reporting enforced some typing on number questions on the server side. If the number was blank it would try to save an invalid number into the database field.

Detecting this case and saving a null for these questions.
