### ISSUE TITLE
Server error on cost reports

### ISSUE THREAD

**Issue by twelch** [Ecotrust/solomon#198]
Note the default cost report for all dates loads ok.  When I change the date slider I get back a 500 error.

https://hapifis.herokuapp.com/reports/crosstab/reef-fish-market-survey/survey-site/cost?startdate=20120913&enddate=20130712

**Comment by twelch** [comment]
Even the default doesn't load now

**Comment by twelch** [comment]
Also all the charts don't seem to be including the first day of data on Oct. 8th.  The slider show's the 8th but it doesn't seem to be inclusive.  We did surveys at fishing village on the 8th and they don't seem to be showing.

**Comment by eknuth** [comment]
Ok, fixed a bunch of things with this.

Date range slider was using the wrong date format and has been switched.  I handled cases where there were no records present for a date range.  

I also added pagination for the responses, so you can page through them all.  I noticed that the actual responses were being included with the respondents and that was slowing things down quite a bit as well as causing our memory error with 30 records.  So the list view only gets the minimal data and is much faster.
