### ISSUE TITLE
Species Weight Grid Question

### ISSUE THREAD

**Issue by sfletche** [Ecotrust/solomon#202]
Currently this Grid question requests both Whole Pounds and Gutted Pounds.
This should change so the user will enter either Whole Pounds OR Gutted Pounds.

Questions about this requirement that come to mind include:

Is the decision to enter Whole or Gutted pounds specific to individual species?
Or is the decision for all species in a gear type category (Traps, Nets, etc)? 

Is it possible for a single Catch Report to contain entries for both Whole pounds AND Gutted pounds?

**Comment by cheryltchen** [comment]
duplicate
