### ISSUE TITLE
Grid col Options losing their Caps

### ISSUE THREAD

**Issue by twelch** [Ecotrust/solomon#21]
When creating a grid col option through the dashboard, it doesn't retain a capital first letter and instead is lowercased

**Comment by twelch** [comment]
Seems to be slugifying.  the title 'Volume (kg)' turned into 'volume-kg'.

**Comment by twelch** [comment]
label is supposed to be a slug, guessing it's mixing things up. See ticket about label not getting created

**Comment by eknuth** [comment]
Fixed and deployed to test.
