### ISSUE TITLE
Surveys not submitting if incomplete ones in list.

### ISSUE THREAD

**Issue by twelch** [Ecotrust/solomon#212]
if you have incomplete surveys and go to submit your complete surveys, it doesn't seem to submit the complete surveys, they're still in the list.  If you remove the incomplete surveys and try again it successfully submits them.

This might only be in cases where the 'ghost' responses are occurring, see next ticket.

**Comment by eknuth** [comment]
Was getting hung up on a unepxected response from the server.  Done and deployed.
