### ISSUE TITLE
'ghost' survey responses

### ISSUE THREAD

**Issue by twelch** [Ecotrust/solomon#213]
as you do your survey, often times you can go to my surveys and there are multiple records that have been created for that survey respondant in the list with sequenced times.  I don't know yet if it's the back button triggering the creations of a new respondant (doesn't look like it), double tapping continue (not that I can tell) or what but what at some point it does happen and I flip over and there's a new entry.  This is happening pretty consistently for folks with the reef fish market survey.

You might save this for last as its a little elusive.  It's not a total dealbreaker, surveyors just have to find the right survey response to marker as complete and delete the rest.

**Comment by eknuth** [comment]
This done and deployed.
