### ISSUE TITLE
App slows down

### ISSUE THREAD

**Issue by twelch** [Ecotrust/solomon#219]
This may be all the work to encode/decode from localstorage once there's a few surveys.  Might not, but after a time the app can really slow down and delays between screens/button presses can be a few second each or more.

**Comment by twelch** [comment]
Slowdown happens after taking 5-6 surveys or often after having the phone on for more than one day doing surveys.  Eventually app just starts to take a lot of time to get from one question to the next as the survey goes on, particularly on the grid questions.

Not sure exactly what's causing but worth investigating at some point.  If this will take more time or should happen as part of another project first or... just say so.

**Comment by jennywalsh** [comment]
Added to Sprintly 118.
