### ISSUE TITLE
sanity check summation

### ISSUE THREAD

**Issue by eknuth** [Ecotrust/solomon#246]
Then 2 screens later when I get to the total page it didn't add then up correctly. I entered a value for all the species using gutted and the last one I did whole. The totals were just listed for whole and the number was incorrect. Nothing for gutted. And then when I went back 2 screens to where I enter the pounds, at first the screen showed only half the species listed and then after about 5-10 secs the rest of them where listed as well. And now without touching anything the arrow is yellow still but when I hit it nothing happens. Had to hit home screen button to get out. Resumed and then went back, same thing happened.

**Comment by cheryltchen** [comment]
duplicate
