### ISSUE TITLE
handle connectivity and other issues on login/registration

### ISSUE THREAD

**Issue by eknuth** [Ecotrust/solomon#250]
Currently handling duplicate users, password errors, password mismatch.  Not handling connection failures.

Report:
Entered my user name and pass word and hit login in and it faded like it was going to log me in and then back to the same screen with me username and pass entered, not logged in. I have no way of getting out of this screen that is easy to regocnize. Hit the back button on the phone, not the app to go back to the previous application. Then opened again and my username and password were gone. Tried to log in again and nothing. Noticed that were I am at right now doesn't have a cell signal, would that matter? Just moved to a location that has a signal and it logged me in.

**Comment by cheryltchen** [comment]
duplicate
