### ISSUE TITLE
Special request!  update hapifis-test

### ISSUE THREAD

**Issue by twelch** [Ecotrust/solomon#263]
I've met some muy importante people that would like to try out HapiFis and I'd like to let them play in the test sandbox in a couple days.  Could you deploy the latest server code to test as well as the mobile app?  The mobile app should connect to test naturally.  Then if you could copy the current surveys over from production to test (the current surveys on test can go away).

This would be very awesome.  Then I'll confirm everything is working well, set them up with an account and pass them the link to the dashboard and to download the apk.  Am I missing anything?

**Comment by eknuth** [comment]
Also need to update the database to a paid instance and migrate.

**Comment by eknuth** [comment]
Ok, updated to latest code and db.  DB promoted to the basic ($9/mo).  Production db isa little beefier with the $50/mo instance.
