### ISSUE TITLE
Duplication of date/time fields

### ISSUE THREAD

**Issue by twelch** [Ecotrust/solomon#27]
The behavior I'm seeing on my galaxy s3 is the text field is already set to the current date or time on load.  Then the date/time tumbler is brought up and is set to the current date or time.  When I then hit the 'set' button, it append a second date or time on top of the originally set on so it reads for example '09:4009:40'

It either shouldn't set the field value the first time or needs to overwrite with the new one properly. maybe both.

Same behavior on price questions with a default value of 0

**Comment by eknuth** [comment]
Fixed and deployed to test.  Default value is still "now", but only shows up once.
