### ISSUE TITLE
Cost chart displaying zeros and can't always see the top

### ISSUE THREAD

**Issue by twelch** [Ecotrust/solomon#295]
When the value is zero it's rendering the zero on the gap between the bar segments, which is confusing.  

Also the total cost value at the top of the Honiara central bar is partially hidden.  The height of the chart could probably be set better

**Comment by eknuth** [comment]
Good to go.  Pulling the zeros and increasing the height.

Might want to consider grouping the costs to reduce the number of series.

**Comment by twelch** [comment]
Yeah can't do much about the number of series, data loses value if we start lumping and surveyors are more likely to miss costs.

Can we put the legend below the table and get all the names showing?  On my mac screen I can't quite see them all, need a third row probably.  With that this is done

**Comment by twelch** [comment]
In addition to moving the legend, I still can't see the top of the bars in the bar charts.
