### ISSUE TITLE
Add market name to respondant list in dashboard

### ISSUE THREAD

**Issue by twelch** [Ecotrust/solomon#299]

**Comment by twelch** [comment]
Add vendor name too

**Comment by jennywalsh** [comment]
Sprintly#34 - assigned to Quinlan.

**Comment by qpfiffer** [comment]
So the RespondantList has responses, and one of the responses has the market name. In the controller where the data is created/displayed I only have access to the URL of the response objects.

I think this is an excellent time for @wraithan to send me some data. For this ticket I just need access to the name of the market when the ResponseList is built.
