### ISSUE TITLE
Change bar charts over to HighCharts

### ISSUE THREAD

**Issue by twelch** [Ecotrust/solomon#312]

**Comment by jennywalsh** [comment]
Added to Sprintly#29

**Comment by twelch** [comment]
Can you review this pull request Edwin?  Thanks.  We'll move away from GitHub tasks soon and want pull requests to be coordinated through Sprint.ly.

**Comment by twelch** [comment]
I mean @eknuth ;)

Can you review this pull request Edwin? Thanks. We'll move away from GitHub tasks soon and want pull requests to be coordinated through Sprint.ly.

**Comment by jennywalsh** [comment]
I connected the GitHub solomon repository with the Solomon product in
Sprintly.  Here's a start of what the connection can do:

Integration with sprint.ly powers closing tickets through commit messages,
updating ticket status via pull request and much more.

On Wed, Nov 13, 2013 at 7:27 PM, Tim Welch notifications@github.com wrote:

> I mean @eknuth https://github.com/eknuth ;)
> 
> Can you review this pull request Edwin? Thanks. We'll move away from
> GitHub tasks soon and want pull requests to be coordinated through
> Sprint.ly.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/Ecotrust/solomon/issues/312#issuecomment-28456668
> .

##
