### ISSUE TITLE
Option ordering

### ISSUE THREAD

**Issue by twelch** [Ecotrust/solomon#38]
Currently editing options after creation can cause the order in the grid to change.  Since Django can't promise ordering to be consistent, need enforced ordering and ability to change it, perhaps via drag/drop just like questions

**Comment by eknuth** [comment]
Ok, added ordering to and drag and drop iu to grid columns.  Doesn't take effect until the question is saved.

**Comment by twelch** [comment]
Can't seem to reorder options, particularly trying on this question to make the volume column last.  http://simarketsurvey.herokuapp.com/dash#/author/volume-and-origin?question=resource-details

Saving just refreshes with the old order

**Comment by eknuth** [comment]
Yeah, it was saving and then reordering on load :(  It's deployed to test.

**Comment by twelch** [comment]
Looks good, let's push it
