### ISSUE TITLE
Wrap text in grid and col

### ISSUE THREAD

**Issue by twelch** [Ecotrust/solomon#39]
Currently labels are shortened with a '...'.  Need to be able to read the full label as things like "Knives/scaler" are shortened to "Knives/sca..." which makes the second part un-interpretable.  Basic line wrap should be fun, up to the survey admin to make them work.

**Comment by eknuth** [comment]
Got the rows to wrap, which helps a lot. I spent some time on the grid headers, but there is a lot going on in there css wise.  I think Tim handled it in the master branch.  I'd like to push this one into the next milestone and see what he did.

**Comment by twelch** [comment]
Yes the rows look good and I've been paring down cols to one or two words so they're ok for now.  Changing to next milestone

**Comment by twelch** [comment]
Shifting to next sprint
