### ISSUE TITLE
Dashboard for viewing survey results

### ISSUE THREAD

**Issue by twelch** [Ecotrust/solomon#41]
Single survey result page
Multiple survey summary page? (paginated, columns)

Let's look at what you've already done for the Mid-Atlantic survey

**Comment by eknuth** [comment]
Have the single survey result page for submitted surveys.  We can add distribution tables for any question.  Anything else for this go around?

**Comment by twelch** [comment]
A few distribution questions would go a long way with Maurice.  I'll ask Kevin which are high priority and get back to you.
