### ISSUE TITLE
Unpack responses

### ISSUE THREAD

**Issue by twelch** [Ecotrust/solomon#42]
We had a discussion that responses should be unpacked into records better suited for querying at the database level.  Looks like everything from grid to yes/no to single select is currently stored as json strings

**Comment by twelch** [comment]
Another reason to unpack is because most values will be used for dashboard reports.  Take a look at the list of queries in this design document.

https://docs.google.com/file/d/0Bygoj3XHCCwBNTBlMURKVXR1dGM/edit?usp=sharing

**Comment by eknuth** [comment]
Everything but grid is unpacked, now.  The mobile app submission was leaving them packed.

**Comment by eknuth** [comment]
Ok, unpacking grid questions for 'currency', 'integer', 'number', 'single-select', 'text', 'yes-no' and multi-select grid question types.  These get a gridAnswer object identified by row and column.

There seem to be some issues with dashes in the grid column label.  In some case it causes a bug with angular.  I'm still looking into it.  They still show up completely in the dash baord and most of the grid answers are unpacked, though.
