### ISSUE TITLE
Previous yes/no and grid answers not loaded when I go back to it

### ISSUE THREAD

**Issue by twelch** [Ecotrust/solomon#44]
When I press the back button most other questions reload the answer I gave.  The yes/no question does not

**Comment by twelch** [comment]
Same with single and multi lists, selections aren't reloaded on back

**Comment by eknuth** [comment]
Tested with single/multiselects, yes-no, grids, timepicker, datepicker,

**Comment by twelch** [comment]
I've confirmed all those mentioned are working.  Grids look like they're not quite there.
- Number values not being reloaded on shellfish grid question "weigh all the containers with resources and without".  They are maintained on the previous grid number question however "total number and weight" with # heaps and weight each.
- Multi-select in grid appears not to reload.  See "Select size classes for each resource".  The single select in the grid questions that follows however does appear to maintain its values.

**Comment by eknuth** [comment]
This is fixed.  Multiselects were a pain and angular didn't like using slugs with dashes in the name to reference objects.  So it was working for most things with a few exceptions. :(
