### ISSUE TITLE
Integer question does not respect integer max value

### ISSUE THREAD

**Issue by twelch** [Ecotrust/solomon#59]
It accepts over 100 for example for question: http://simarketsurvey-test.herokuapp.com/static/survey/mobile.html#/survey/vendor-profile/percent-to-other-way/offline

**Comment by twelch** [comment]
I've confirmed that the input box turns red on an invalid value, but on the phone at least it still lets me continue.

**Comment by eknuth** [comment]
Confirmed that this is fixed in the app on test.

**Comment by twelch** [comment]
Go ahead and push to production

**Comment by eknuth** [comment]
Ok, this is tested in production.

**Comment by eknuth** [comment]
This question was set to a max of 365, but I changed it to 100.
