### ISSUE TITLE
Ability to delete partial or unsubmitted surveys

### ISSUE THREAD

**Issue by twelch** [Ecotrust/solomon#60]

**Comment by eknuth** [comment]
Clicking on a completed surveys gives you the option to resume or delete.

**Comment by twelch** [comment]
I don't seem to be getting this option on the production app on the phone or in the browser.  All if have to do is click the survey?

Please reassign to me to check instead of completing, thanks

**Comment by eknuth** [comment]
Missed a push.  You can resume/delete after tapping the completed survey.
