### ISSUE TITLE
Support for one or more size classes for each resource

### ISSUE THREAD

**Issue by twelch** [Ecotrust/solomon#66]
User selects one or more resources (multi-select).  For each resource, user then selects one or more size classes (multi-select, classes are not the same for each resource so need to ask for each resource).  These answers will form the rows of the grid questions to come e.g.:

Mud Crab - 20cm
Mud Crab - 30cm
Coconut Crab - 25cm
Coconut Crab - 45cm

Then need to be able to create one or more grid questions that can reference this as a 'previous answer'.  For example I'll have a grid question with province, region, village, a grid with wholesale, retail price, a grid with size and weight, and so on.  All will be answered for all resource/size class combinations.

**Comment by eknuth** [comment]
Ok, looks like we need multi select for grid questions, and then to use that output to create grids for each resource and size class.

**Comment by twelch** [comment]
Yes that sounds right

**Comment by eknuth** [comment]
Ok, this should be good to go.  Check out the shellfish survey on test.  I added a grid question for location that pulls it's rows from the size class multiselect.  It uses ":" to designate which grid label to use, for instance this one is "select-size-classes:size-class".

**Comment by twelch** [comment]
@eknuth It's not currently going past the first multi-select for me for the size section, phone or laptop, cache/storage cleared.  Will peek at in the morning.

**Comment by eknuth** [comment]
Was that on test?  Looks like it had a bogus question in there.  It's fixed and working for me on dev/test phone and laptop.  Don't forget to update your surveys.

**Comment by twelch** [comment]
Thank yes that was test.  I update my surveys religiously :-)  will dig in tomm and review these. Ill be sitting at LAX all day...

**Comment by twelch** [comment]
Appears to work well in testing.  One thing threw me, by default the first row 'select option' is selecred by default.  It shouldn't be selectabselectable optimally at least not by default

**Comment by eknuth** [comment]
Yeah, not sure what's up with that.  It's a placeholder option and doesn't come through as being selected in the next question.  It was bugging me, too.

**Comment by eknuth** [comment]
I'm going to open another ticket for the placeholder and I think this ticket is good to be closed.

**Comment by twelch** [comment]
Closing
