### ISSUE TITLE
Create production phone app

### ISSUE THREAD

**Issue by twelch** [Ecotrust/solomon#69]
Would be nice to keep the test app as well on a separate apk.  Push these apk's to Heroku if possible?

**Comment by twelch** [comment]
use https too

**Comment by eknuth** [comment]
Two versions are up at with https at:
https://simarketsurvey.herokuapp.com/static/simarket.apk
https://simarketsurvey.herokuapp.com/static/simarket-test.apk

Right now you can only install one at a time.  There is a link on the "home" page of the app to update to either version.  You can switch back and forth and up/downgrade at will.

**Comment by twelch** [comment]
Ooh fancy. I saw that in the bottom left and wondered

**Comment by twelch** [comment]
Survey author (/dash) is not loading under https, or at least the list of surveys in the menu isn't.  Reopening.

**Comment by twelch** [comment]
Actually I'll create a new ticket.  Closing
