### ISSUE TITLE
Need button to clear cache

### ISSUE THREAD

**Issue by twelch** [Ecotrust/solomon#74]
Clearing the surveys and any ongoing ones.  I found that I updated a survey and upon trying it again it wasn't rendering a particular grid question even though it worked fine on my laptop top.  No dice no matter how many times I updated the surveys or restarted the app.

I went to settings->manage applications and cleared the app cache which did the trick.  Guess something was in a weird state.  Would be nice to be able to do this in the app.

**Comment by eknuth** [comment]
Added a settings button.  hapifis local storage is cleared and the app is reloaded.  User will have to log in again.
