### ISSUE TITLE
Integer question type allows decimal

### ISSUE THREAD

**Issue by twelch** [Ecotrust/solomon#77]
I would recommend adding a decimal or float question type.  Integer is whole number only and should be enforced as such.

**Comment by twelch** [comment]
For now I'll keep making everything integer to enforce it's a number and get a keypad.  Will need to transition questions over once this happens.

**Comment by twelch** [comment]
On a related note, I feel like 0 is a reasonable default min but a default max of 365 doesn't make sense.  Consider allowing a blank and making that the default.

**Comment by twelch** [comment]
Field turns red when I add a decimal, but still allowing me to continue.

**Comment by twelch** [comment]
This is on production

**Comment by eknuth** [comment]
Interesting.  The question was not validating on the desktop, but allowing submission in the app.
