### ISSUE TITLE
0 value not being accepted

### ISSUE THREAD

**Issue by twelch** [Ecotrust/solomon#8]
Honiara Volume survey, seeing behavior with these questions:

Ice purchase cost (http://simarketsurvey-test.herokuapp.com/static/survey/mobile.html#/survey/volume-and-origin/ice-cost/)
Days of storage (http://simarketsurvey-test.herokuapp.com/static/survey/mobile.html#/survey/volume-and-origin/days-storage/)

Entering 0 does not enable the continue button, even though integer min is set to 0.

Pressing enter however does take you to the next question, needs to be synched with state of continue

**Comment by eknuth** [comment]
Fixed and tested in test.
