### ISSUE TITLE
Blocker - unable to go back and edit completed surveys

### ISSUE THREAD

**Issue by twelch** [Ecotrust/solomon#81]
The issue is that after leaving a survey, really whether it's completed or not, and you go back into the survey to finish it or just edit it, you can't navigate back to previous questions.  What happens is once back in the survey, if you touch the back button, it doesn't go to the previous question, it goes back to the survey menu.  So there's no way to really access further back in the survey with the back button, except the first time you're doing the survey.

**Comment by eknuth** [comment]
Added a back button and a method for moving back in the survey, handling skipped questions.

**Comment by twelch** [comment]
Works great, thanks mucho.
