### ISSUE TITLE
Allows me to submit incomplete surveys

### ISSUE THREAD

**Issue by twelch** [Ecotrust/solomon#82]
Realizing I can submit incomplete surveys.  Would like to see that be tracked and that state exposed in the Completed surveys menu listing so you can easily see which ones you haven't finished by scanning the list.  Coming back to complete partial surveys will come up on occasion Kellington has said.

Related to that the menu name 'Completed surveys' is no longer accurate.  We should consider changing it, perhaps to "My Surveys"?

**Comment by twelch** [comment]
Still submits incomplete surveys though. Can this be prevented so it submits only the complete ones?

**Comment by eknuth** [comment]
Oh sure.  I thought we wanted to keep the behavior for submitting.

**Comment by eknuth** [comment]
Incompletes are left behind after a submit and can be resume or deleted.

**Comment by twelch** [comment]
Works well, thanks
