### ISSUE TITLE
Times shown on dashboard are not Solomon time

### ISSUE THREAD

**Issue by twelch** [Ecotrust/solomon#86]
Think they're pacific US.  Should be Solomon time.

**Comment by twelch** [comment]
Is this getting used, the timestamps look off on the list view page and the respondant page. For example here's a real market survey from yesterday:

http://simarketsurvey.herokuapp.com/dash#/RespondantDetail/volume-and-origin/offline_1373948177406

Here's the timestamp shown, which I presume is the timestamp for submission to the server?
timestamp
07/17/2013 @ 2:23AM

Here's the real survey date and time answers as a reference:
Survey date: 2013-07-16
Survey time: 15:16

**Comment by twelch** [comment]
The survey was submitted probably 30-45 minutes after the survey date and time shown.

**Comment by eknuth** [comment]
Ok.  So the timestamp is when it is submitted to the server.  The timezone is set to UTC+11, which might example how we got to 11 hrs later on the 17th.  Looks like it is offset by 11 hours.  Maybe it was expecting UTC...

Survey Date and Survey Time are set from the clock on the device, which I assume is accurate and set to local time, right?

**Comment by twelch** [comment]
Yes the devices enters the local time
