### ISSUE TITLE
Delete question bug

### ISSUE THREAD

**Issue by twelch** [Ecotrust/solomon#94]
When deleting a question from the end of a survey, it goes through a lengthy reorder process seemingly doing a reorder on the entire survey.  After this reorder the first question of the survey was then missing instead of the one I chose to delete. 

A refresh of the dash page at this point brought up another lengthy reorder process seemingly touching every question again.  Once complete, things are as they should be, the first question is back and the proper question is deleted.

So there's some intermediate strangeness but ultimately the final state is correct after an additional refresh.

This happened when I did a delete yesterday and happened again today, so 2 for 2.

**Comment by eknuth** [comment]
Ok, I can reproduce this.  I'll get to the bottom of it.

**Comment by eknuth** [comment]
There was a bug in the delete code that would remove the first question from the array of questions, no matter what you were trying to delete.  This would cause every question to be reordered.  Then when you refreshed it would grab the correct list of questions, notice that they were off by one and reorder them again.  It's good to go on production, now.
