### ISSUE TITLE
Change dates in surveys to day-month-year

### ISSUE THREAD

**Issue by twelch** [Ecotrust/solomon#95]

**Comment by twelch** [comment]
Or maybe make configurable what order is wanted

**Comment by twelch** [comment]
Done except, can we change the date spinner to also be day month year, like 18 Jul 2013?

**Comment by twelch** [comment]
The date picker also seems to be setting the date value to for example 2013-07-08

**Comment by eknuth** [comment]
Looks like the datepicker format is tied to the phone's localization settings: http://stackoverflow.com/questions/7372038/is-there-any-way-to-change-input-type-date-format

I don't see any way to change that in my phone though...
